
spring:
  session:
    store-type: 'none'
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
  datasource:
    platform: 'postgres'
    url: 'jdbc:postgresql://localhost/publications'
    username: 'publications'
    password: 'publications'
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true

server:
  servlet:
    session:
      cookie:
        max-age: 259200s
      timeout: 259200s
